export const recommendations = [
  {
    title: '!Weather',
    description: 'The best weather widgets for your iPhone.',
    link: 'https://notbor.ing/product/weather',
    image: '/apps/weather.png',
    type: 'app',
  },
  {
    title: "Learnability Isn't Enough: How to Design Apps That Are Easy to Use in the Long Run, Not Just the First Run",
    description: 'This helps you create apps that are both easy to learn and efficient in long-term use.',
    image: 'https://m.media-amazon.com/images/I/61rcN28uGIL._SL1360_.jpg',
    link: 'https://amzn.eu/d/2NkXZFS',
    type: 'book',
  },
  {
    title: 'Hooked: How to Build Habit-Forming Products',
    description: 'How to turn your product into a habit-forming one.',
    image: 'https://m.media-amazon.com/images/I/81L8JOVXJtL._SL1500_.jpg',
    link: 'https://amzn.eu/d/eR9KebV',
    type: 'book',
  },
  {
    title: 'NotchNook',
    description:
      'Transforms the MacBook notch into a functional utility center with widgets, live actions, and file storage.',
    link: 'https://lo.cafe/notchnook',
    image: '/apps/notchnook.png',
    type: 'app',
  },
  {
    title: 'Notion',
    description: 'My go-to workspace for notes, project management, and knowledge organization. Incredibly versatile.',
    link: 'https://www.notion.com/',
    image: '/apps/notion.png',
    type: 'app',
  },
  {
    title: "The Pep Revolution: Inside Guardiola's Manchester City",
    description: "The long-awaited, access-all-areas story of Pep Guardiola's time at Manchester City.",
    image: 'https://m.media-amazon.com/images/I/81PYFqXpHhL._SL1500_.jpg',
    link: 'https://amzn.eu/d/jgiM6dm',
    type: 'book',
  },
  {
    title: 'The Social Dilemma',
    description: 'A must-watch documentary exploring the dangerous human impact of social networking.',
    image: 'https://upload.wikimedia.org/wikipedia/en/2/27/Social_dilemma_xlg.jpg',
    link: 'https://www.netflix.com/title/81254224',
    type: 'film',
  },
  {
    title: 'Reeder',
    description: 'Elegant RSS reader rebuilt for modern use. Perfect for staying updated with blogs and news sources.',
    link: 'https://reederapp.com/',
    image: '/apps/reeder.png',
    type: 'app',
  },
  {
    title: 'Sleeve',
    description: "Displays beautiful album artwork on your desktop for whatever music you're currently playing.",
    link: 'https://replay.software/sleeve',
    image: '/apps/sleeve.png',
    type: 'app',
  },
];
